# Generated by Django 5.0.1 on 2024-01-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waitlistformsettings',
            old_name='Waitlist_form_page',
            new_name='waitlist_form_page',
        ),
    ]
