# Generated by Django 4.2.15 on 2024-08-19 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_post_company_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followingrelationships',
            name='company_follower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='following', to='api.company'),
        ),
        migrations.AlterField(
            model_name='followingrelationships',
            name='company_following',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followers', to='api.company'),
        ),
    ]
