# Generated by Django 4.1.8 on 2024-01-21 17:39

import cloudinary.models
from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500, null=True)),
                ('message', wagtail.fields.RichTextField(blank=True)),
                ('avatar', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='hero_section_message',
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_mission',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_promise',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='our_vision',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
