# Generated by Django 4.1.8 on 2024-02-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faqs_alter_testimonial_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQs',
            new_name='Faq',
        ),
    ]
